declare module "bcdice-js";
declare module "skyway-js";
declare module "jszip";
declare module "file-saver";
declare module "vuedraggable";
declare module "vue-slider-component";
declare module "mustache";
declare module "mathjs";
declare module "crypto-js";
declare function parseInt(s: string, radix?: number): number;
